Repository TheNerdful8/Lecture2Gether, pull requests merged in 2020-07, with the labels that each got.

#79 Add faster playback rate
  lecture2gether-vue/src/components/Player.vue
Labels: enhancement, frontend, good first issue

#73 Add design for video meta data
  lecture2gether-vue/src/components/Player.vue
  lecture2gether-vue/src/components/Toolbar.vue
  lecture2gether-vue/src/components/VideoMetaData.vue
  lecture2gether-vue/src/views/Room.vue
Labels: enhancement, frontend

#84 Add the ability to play public google drive videos
  .github/workflows/backend_test.yml
  README.md
  lecture2gether-vue/src/components/Toolbar.vue
  lecture2gether-vue/src/mediaURLs.ts
  lecture2gether_flask/app.py
  lecture2gether_flask/meta_data_provider.py
  lecture2gether_flask/test.py
Labels: backend, enhancement, frontend
