Repository TheNerdful8/Lecture2Gether, pull requests merged in 2020-06, with the labels that each got.

#33 Clean whitespaces in backend
  lecture2gether_flask/app.py
Labels: refactoring

#34 Update README.md
  README.md
Labels: bug

#32 Emit number of users in room
  lecture2gether-vue/src/App.vue
  lecture2gether-vue/src/api.ts
  lecture2gether-vue/src/components/Toolbar.vue
  lecture2gether-vue/src/plugins/socket.io.ts
  lecture2gether-vue/src/plugins/store/rooms.ts
  lecture2gether_flask/app.py
Labels: enhancement

#46 Add a Node.js CI badge
  README.md
Labels: good first issue

#49 Add PrivacyPolicy Dialog
  lecture2gether-vue/src/components/Lecture2GetherFooter.vue
  lecture2gether-vue/src/components/PrivacyPolicy.vue
Labels: enhancement, frontend

#61 Fix: Leave room before db access
  lecture2gether_flask/app.py
Labels: backend, bug

#51 Implement sentry error reporting
  README.md
  docker/settings.json
  lecture2gether-vue/package-lock.json
  lecture2gether-vue/package.json
  lecture2gether-vue/src/main.ts
  lecture2gether-vue/src/plugins/store/settings.ts
  lecture2gether_flask/app.py
  lecture2gether_flask/poetry.lock
  lecture2gether_flask/pyproject.toml
Labels: backend, enhancement, frontend
